name: build installer package
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - run: installer/_solution_build.cmd
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.16.1'
      - run: installer/_build.cmd
      - uses: actions/upload-artifact@v2
        with:
          path: installer/build/tsftutcode-*.exe
